services:
  teama.devfollow.api:
    image: ${DOCKER_REGISTRY-}teamadevfollowapi
    build:
      context: .
      dockerfile: TeamA.DevFollow.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://teama.devfollow.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://teama.devfollow.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  teama.devfollow.seq:
   image: datalust/seq:2024.3
   environment:
       ACCEPT_EULA: "Y"
   volumes:
     - ./.containers/seq_data:/data
   ports:
    - 8080:80
    - 5341:5341 

  teama.devfollow.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
  
