name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Enable centralized package management (workaround)
        run: echo "NUGET_ENABLE_EXPERIMENTAL_CPM=1" >> $GITHUB_ENV

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore TeamA.DevFollow.sln --verbosity detailed

      - name: Build
        run: dotnet build TeamA.DevFollow.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test TeamA.DevFollow.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish TeamA.DevFollow.sln --configuration Release --no-restore --no-build
