name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.0.202"  # Use specific version instead of "9.x"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to support proper version computation

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Display .NET info
        run: dotnet --info
      
      - name: Restore
        run: dotnet restore api/TeamA.DevFollow.sln

      - name: Build
        run: dotnet build api/TeamA.DevFollow.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test api/TeamA.DevFollow.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish api/TeamA.DevFollow.sln --configuration Release --no-restore --no-build